# Generated by Django 4.2.16 on 2024-12-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_medica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={},
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_medica.medico'),
        ),
    ]
