# Generated by Django 4.2.16 on 2024-12-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_medica', '0005_rename_leido_notificacion_leida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='leida',
            new_name='leido',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
