# Generated by Django 4.2.16 on 2024-12-17 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_medica', '0006_rename_leida_notificacion_leido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='recepcionista',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono solo debe contener números.', regex='^\\d+$')]),
        ),
    ]
