# Generated by Django 4.2.16 on 2025-11-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_medica', '0007_alter_medico_telefono_alter_paciente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha_medica.reserva'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
